from .common import COMMON_RULES, NATURAL_TONE, CONFIRMATION_INSTRUCTION, SUCCESS_INSTRUCTION
from .general import GENERAL_AGENT_SYSTEM_PROMPT
from .project import PROJECT_AGENT_SYSTEM_PROMPT
from .task import TASK_AGENT_SYSTEM_PROMPT
from .supervisor import SUPERVISOR_SYSTEM_PROMPT

__all__ = [
    "COMMON_RULES",
    "NATURAL_TONE",
    "CONFIRMATION_INSTRUCTION",
    "SUCCESS_INSTRUCTION",
    "GENERAL_AGENT_SYSTEM_PROMPT",
    "PROJECT_AGENT_SYSTEM_PROMPT",
    "TASK_AGENT_SYSTEM_PROMPT",
    "SUPERVISOR_SYSTEM_PROMPT",
]